shell
refactored shell script slightly

diff --git a/src/dam b/src/dam
--- a/src/dam
+++ b/src/dam
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 # Script used to execute AudioMatching.java application
 # Arguments passed in command line will be passed into application
@@ -8,15 +8,22 @@ javac AudioMatching.java
 echo Done.
 echo Executing...
 
-# Check if both arguments are files
-if [ "$1" == "-f" -a "$3" == "-f" -a -f "$2" -a -f "$4" ]
-	then
-	# Pass file paths as arguments to Java Application
-	java AudioMatching "$2" "$4"
+# Check if 4 arguments
+if [ "$#" == 4 ]
+    then 
+    # Check if arguments are files
+    if [ "$1" == "-f" -a "$3" == "-f" -a -f "$2" -a -f "$4" ]
+        then
+        # Pass file paths as arguments to Java Application
+        java AudioMatching "$2" "$4"
+    else
+        # Write to stderr if non files
+        echo 'ERROR : Paths are not files.' >&2
+        exit 1
 else
-	# Write to stderr if non files
-	echo 'ERROR : NOT A FILE.' >&2
-	exit 1
+	# Write to stderr if in correct command
+    echo 'ERROR : Incorrect command.' >&2
+    exit 1
 fi
 
 echo Done.
