Added a termination check

diff --git a/src/dam b/src/dam
--- a/src/dam
+++ b/src/dam
@@ -118,8 +118,18 @@ validateFilePaths() {
     # Validate the paths
     if [ -f $FILE1 -a -f $FILE2 ];
         then
+
         # Pass file paths as arguments to Java Application
         java AudioMatching $FILE1 $FILE2
+
+        # Check the exit status of the proces
+        # Terminate if non-zero
+        OUT=$?
+        if [ $OUT -ne 0];
+            then
+            exit 1
+        fi
+
     else
         # Write to stderr if non files
         error "1" "validateFilePaths"
